### ISSUE TITLE
Feature: Automatic Leniency Mode

### ISSUE THREAD

**Issue by Kyrobi** [CaptainObvious0/NoCheatPlus#21]
### Describe the features of this added check
A system that will dynamically adjust vl values for each check based on ping / server tps.
I know Mark's config is pretty good, but I feel like there should be something that does it dynamically to a point.

### Description of how this check would work
Take values from the config, and +/- the value based on TPS / ping. Since the config is already really good, the automatic system can use the config as a framework for the values to be adjusted. This way, Mark's config can still be really useful in providing information for NCP in what values to change.

### Any extra information about what should be added? (Config options...)
NCP's movement checks are literally too overpowered. Of the 4 other paid anti-cheats for 1.13, NCP was the only one able to successfully block NoFall and Jesus correctly.

Although because of the overpowered nature, the checks might be a little too strict in some cases. Sadly these FPs are rare occurrence that I can't get the info to make an issue report on.

**Comment by CaptainObvious0** [comment]
Interesting concept, but I would still be in favor of ping and tps accommodation after violation. I described the addition of tps and ping conditions being added to the cancel action, which could help with reducing false positives for server/player lag.

If you could describe to me the benefit between adjusting vl before actions rather than adjusting actions after vl, I could possibly see the bigger picture.

In terms of being too strict, that is something I want to tackle in the future. It’s not the strictness that needs to be fixed, but the constant low vl false positive.

Just a fyi, there is no relation/connection between this project and @MarkElf’s config.

**Comment by Kyrobi** [comment]
Oh.. rip. I typed it thinking that there's no built-in leniency at all. If that's the case, then this entire suggestion is pretty invalid lol

**Comment by CaptainObvious0** [comment]
There is some built in leniency for some checks. Other than that you can use ConditionalCommands to use conditions on commands. In the future I want to extend that to be able to apply conditions to cancel as well.

My question again would be what’s the benefit in adjusting vl before actions rather than executing actions based on conditions. (Before vs After)

**Comment by Kyrobi** [comment]
I don't really know how this vl adjusting stuff works, but here are probable reasons:

1. Staff won't get as many vl notifications from players.
2. The player's actions won't get cancel from vl reaching the limits first. That way, it's perceived that the AC isn't being too strict.

I don't even know lol, feel free to close this suggestion.

**Comment by CaptainObvious0** [comment]
1. Conditions could be applied before notifying staff, since logging can be done through a command. 

2. Cancel conditions could solve this issue.

I’ll close the issue. I just wanted to hear what you had to say about my comments. Myself, I would rather apply conditions to actions after rather than before, keeping violations consistent. Going through each check would be time consuming and I would rather give more control to the user on how to handle a violation.
