### ISSUE TITLE
Falling to the magma block fly protection bug

### ISSUE THREAD

**Issue by andris155** [CaptainObvious0/NoCheatPlus#3]
https://www.youtube.com/watch?v=kwBKlEX_oF0

**Comment by CaptainObvious0** [comment]
A couple of questions before:
1. Does this issue only happen with my fork?
2. Does this only occur on 1.13 or is it on all versions?

I'll have to look deeper on what actually causing these violations. Thanks for the report.

**Comment by andris155** [comment]
1. I tested only this NocheatPlus fork.
2. Paper 1.13.2

I use this NoCheatPlus config: https://www.mc-market.org/resources/475/

**Comment by CaptainObvious0** [comment]
I'll be working on a fix soon. This seems to be an issue with NoCheatPlus itself, and not a result of the fork.

**Comment by CaptainObvious0** [comment]
From my testing, the issue occurs only on 1.13. Therefore it must be an issue with the materials list. 

Switching this to issues with 1.13 [Add new blocks]

**Comment by CaptainObvious0** [comment]
Magma blocks seem to be unique in the case of 1.13 blocks, since the block has full block margins. 

According to the tags during testing, it seems that walking on the block fails the expected y distance. For now I'll just add an "exemption" to walking on these blocks, while I do more testing to see exactly what the issue is.

**Comment by CaptainObvious0** [comment]
Spent more time on this issue then I probably should have. Please add `MAGMA_BLOCK: default+ground` to the bottom of your config under blocks.overrideflags
