### ISSUE TITLE
Elytra + Riptide Trident Fly FP

### ISSUE THREAD

**Issue by Kyrobi** [CaptainObvious0/NoCheatPlus#8]
When a user is in water (With elytra + trident with riptide 3) and decides to use the riptide to launch themselves out of the water, It flags them for fly. This essentially makes riptide 3 useless.

NCP Version: 

---- Version information ----
#### Server ####
git-Paper-588 ~MC: 1.13.2~
detected: 1.13.2
#### NoCheatPlus ####
Plugin: 3.16.1-SNAPSHOT-b1153-CustomFork
MCAccess: 1.4.5-1.12.2|? / CB-Reflect

**Comment by CaptainObvious0** [comment]
Thanks for the report. I'll investigate this later.

**Comment by CaptainObvious0** [comment]
Upon further investigation, looks like this can be fixed without any major changes, using `isRiptiding` event. 

Since riptide has multiple enchantment levels, I'll need to adjust its allowed vertical and horizontal speed based on its level. I'll be trying to work this similar to how nocheatplus handles the depth strider enchantment.

**Comment by CaptainObvious0** [comment]
Latest changes to survivalfly should fix normal movements. Extreme movements (bringing yourself super high into the air) and using riptide with elytra still need to be fixed. Any movement without elytra should be reported back here.

I also want to note that these changes haven't been fine tuned to actual speeds. The main goal right now would be compatibility over cheat protection. 

You can build it yourself or use the download link here: https://www.dropbox.com/s/hv97zsi1e9kj28g/NoCheatPlus-CustomFork-vBETA.jar?dl=0
